「ActiveStorage で画像アップロードを実装する」の課題
cellotak/fjord-books_app-2023 pull request #5
Opened 2023-08-28 05:36 UTC by cellotak

「[ActiveStorage で画像アップロードを実装する](https://bootcamp.fjord.jp/practices/146)」の課題として、books_appにActiveStorageを用いて画像アップロード機能を実装します。

必須要件と歓迎要件はそれぞれ以下で、チェックが入っている項目が完了しています。(プラクティスのページにも記載あります。)

## 必要要件
- [ ] ユーザーが自分のアイコン画像をアップロードできるようにする
- [ ] ユーザー一覧画面とユーザー詳細画面にアイコンを表示する（未アップロードなら何も表示しない）
- [ ] 画像を表示する際、大きすぎる画像は適切なサイズにリサイズする（ファイルの容量を小さくしてネットワークの負荷を減らす）
- [ ] 画像アップロード用に追加した項目はi18nのYAMLファイルを編集して項目名を表示させよう（英語化は考慮不要）
- [ ] 一覧画面に画像を表示させる場合はN+1問題を起こさないようにしよう
- [ ] ユーザー一覧画面とユーザー詳細画面のスクリーンショットを載せる
- [ ] rubocopとerblintをパスさせる（要スクリーンショット）

## 歓迎要件
- [ ] プロフィール編集画面にも現在設定されているアイコンを表示する
- [ ] アップロード可能なファイルはjpg, png, gifの3種類だけに限定する

2023-08-28 08:06 UTC, cellotak commented on app/views/users/_user.html.erb
> +
## アカウント登録後この部分でエラーが発生します。

![image](https://github.com/cellotak/fjord-books_app-2023/assets/65953037/18dd6756-4ccc-46f2-82e5-42b320055b2e)


画像含めてアカウント情報をPOSTしたときのRailsログです。

```
Started POST "/users" for 127.0.0.1 at 2023-08-28 16:53:50 +0900
Processing by Devise::RegistrationsController#create as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"avatar"=>#<ActionDispatch::Http::UploadedFile:0x00007f1f66ae1460 @tempfile=#<Tempfile:/tmp/RackMultipart20230828-92659-6pdou2.png>, @original_filename="CelloTAKロゴ_アイコン用.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"user[avatar]\"; filename=\"CelloTAK\xE3\x83\xAD\xE3\x82\xB4_\xE3\x82\xA2\xE3\x82\xA4\xE3\x82\xB3\xE3\x83\xB3\xE7\x94\xA8.png\"\r\nContent-Type: image/png\r\n">, "email"=>"avatar2@test.com", "name"=>"avatar2", "postal_code"=>"", "address"=>"", "self_introduction"=>"", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"アカウント登録"}
  TRANSACTION (0.0ms)  begin transaction
  User Exists? (0.1ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "avatar2@test.com"], ["LIMIT", 1]]
  User Create (0.2ms)  INSERT INTO "users" ("email", "encrypted_password", "reset_password_token", "reset_password_sent_at", "remember_created_at", "created_at", "updated_at", "name", "postal_code", "address", "self_introduction") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)  [["email", "avatar2@test.com"], ["encrypted_password", "[FILTERED]"], ["reset_password_token", "[FILTERED]"], ["reset_password_sent_at", "[FILTERED]"], ["remember_created_at", nil], ["created_at", "2023-08-28 07:53:50.524279"], ["updated_at", "2023-08-28 07:53:50.524279"], ["name", "avatar2"], ["postal_code", ""], ["address", ""], ["self_introduction", ""]]
  ActiveStorage::Blob Load (0.1ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" INNER JOIN "active_storage_attachments" ON "active_storage_blobs"."id" = "active_storage_attachments"."blob_id" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 3], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]
  ActiveStorage::Attachment Load (0.0ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 3], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]
  ActiveStorage::Blob Create (0.2ms)  INSERT INTO "active_storage_blobs" ("key", "filename", "content_type", "metadata", "service_name", "byte_size", "checksum", "created_at") VALUES (?, ?, ?, ?, ?, ?, ?, ?)  [["key", "kd2vf8ykgb0u6yqht339qkbqqxy8"], ["filename", "CelloTAKロゴ_アイコン用.png"], ["content_type", "image/png"], ["metadata", "{\"identified\":true}"], ["service_name", "local"], ["byte_size", 24109], ["checksum", "N0zUYdlU4lEBebLJlSHKIA=="], ["created_at", "2023-08-28 07:53:50.540138"]]
  ActiveStorage::Attachment Create (0.2ms)  INSERT INTO "active_storage_attachments" ("name", "record_type", "record_id", "blob_id", "created_at") VALUES (?, ?, ?, ?, ?)  [["name", "avatar"], ["record_type", "User"], ["record_id", 3], ["blob_id", 1], ["created_at", "2023-08-28 07:53:50.541603"]]
  User Update (0.2ms)  UPDATE "users" SET "updated_at" = ? WHERE "users"."id" = ?  [["updated_at", "2023-08-28 07:53:50.543004"], ["id", 3]]
  TRANSACTION (6.3ms)  commit transaction
  Disk Storage (0.6ms) Uploaded file to key: kd2vf8ykgb0u6yqht339qkbqqxy8 (checksum: N0zUYdlU4lEBebLJlSHKIA==)
[ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 608eec30-69d0-4bf8-afd9-86fd11e78992) to Async(default) with arguments: #<GlobalID:0x00007f1f6458bb70 @uri=#<URI::GID gid://books-app/ActiveStorage::Blob/1>>
Redirected to http://127.0.0.1:3000/books
Completed 303 See Other in 227ms (ActiveRecord: 7.7ms | Allocations: 34828)


[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992]   ActiveStorage::Blob Load (0.2ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992] Performing ActiveStorage::AnalyzeJob (Job ID: 608eec30-69d0-4bf8-afd9-86fd11e78992) from Async(default) enqueued at 2023-08-28T07:53:50Z with arguments: #<GlobalID:0x00007f1f64483660 @uri=#<URI::GID gid://books-app/ActiveStorage::Blob/1>>
Started GET "/books" for 127.0.0.1 at 2023-08-28 16:53:50 +0900
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992] Skipping image analysis because the ruby-vips gem isn't installed
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992]   TRANSACTION (0.1ms)  begin transaction
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992]   ActiveStorage::Blob Update (0.2ms)  UPDATE "active_storage_blobs" SET "metadata" = ? WHERE "active_storage_blobs"."id" = ?  [["metadata", "{\"identified\":true,\"analyzed\":true}"], ["id", 1]]
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992]   TRANSACTION (4.7ms)  commit transaction
[ActiveJob] [ActiveStorage::AnalyzeJob] [608eec30-69d0-4bf8-afd9-86fd11e78992] Performed ActiveStorage::AnalyzeJob (Job ID: 608eec30-69d0-4bf8-afd9-86fd11e78992) from Async(default) in 61.45ms
Processing by BooksController#index as TURBO_STREAM
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
  Rendering layout layouts/application.html.erb
  Rendering books/index.html.erb within layouts/application
  Book Load (0.1ms)  SELECT "books".* FROM "books" ORDER BY "books"."id" ASC LIMIT ? OFFSET ?  [["LIMIT", 25], ["OFFSET", 0]]
  ↳ app/views/books/index.html.erb:4
  Rendered books/index.html.erb within layouts/application (Duration: 1.8ms | Allocations: 945)
  Rendered layout layouts/application.html.erb (Duration: 4.2ms | Allocations: 3671)
Completed 200 OK in 7ms (Views: 4.6ms | ActiveRecord: 0.1ms | Allocations: 5417)
```

ビューで呼び出そうとすると、以下のエラー画面が表示されます。

![image](https://github.com/cellotak/fjord-books_app-2023/assets/65953037/50baa401-21e5-43cc-9532-8f95c1deb978)

この時のRailsログです。

``` 
Started GET "/users" for 127.0.0.1 at 2023-08-28 16:54:37 +0900
Processing by UsersController#index as HTML
  User Load (0.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
  Rendering layout layouts/application.html.erb
  Rendering users/index.html.erb within layouts/application
  User Load (0.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ? OFFSET ?  [["LIMIT", 25], ["OFFSET", 0]]
  ↳ app/views/users/index.html.erb:4
  ActiveStorage::Attachment Load (0.0ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = ? AND "active_storage_attachments"."record_type" = ? AND "active_storage_attachments"."name" = ? LIMIT ?  [["record_id", 1], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]
  ↳ app/views/users/_user.html.erb:5
  Rendered users/_user.html.erb (Duration: 6.9ms | Allocations: 3087)
  Rendered users/index.html.erb within layouts/application (Duration: 8.6ms | Allocations: 4172)
  Rendered layout layouts/application.html.erb (Duration: 8.7ms | Allocations: 4259)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 0.3ms | Allocations: 6018)



ActionView::Template::Error (Can't resolve image into URL: undefined method `persisted?' for nil:NilClass):
    2:
    3:   <p>
    4:     <strong><%= User.human_attribute_name(:avatar) %>:</strong>
    5:     <%= image_tag user.avatar %>
    6:   </p>
    7:
    8:   <p>

app/views/users/_user.html.erb:5
app/views/users/index.html.erb:6
app/views/users/index.html.erb:4
```

2023-08-28 08:19 UTC, morimorihoge commented on app/views/users/_user.html.erb
> +
定例で聞いた範囲だと、

* /storageの下にディレクトリ構成はできて、ファイルは保存されているらしい
* View側でuser.avatarを参照しようとするとエラーが発生する

という感じなのは把握しました。

`rails console` で当該userのインスタンスを取得して、 `user.avatar` がそもそもnilでないかどうかを確認してみると位以かも？  
※エラー内容的にはnilエラーなので、ActiveStorage的にDB側に保存が正常にされていない可能性もありそう。

2023-08-28 08:22 UTC, morimorihoge commented on app/views/users/_user.html.erb
> +
もしusersとして保存されているデータのうち、どれかに正常でないデータがあってそれが原因でエラーになっている場合は、 `web-console` gemとかを入れてみて、例外が発生した瞬間のdebug consoleからuser.avatarとかしてデータ側のエラーなのかを特定することはできるかもです。

2023-08-28 08:23 UTC, morimorihoge commented on app/views/users/_user.html.erb
> +
あとは、showで一つずつ見てみるとか（やや場当たり的ですが、データ1件ずつでチェックするという意味で

2023-08-28 08:24 UTC, morimorihoge commented on app/views/users/_user.html.erb
> +
原因としてありそうな方向性として、

* 正常なデータもあるが、異常なデータもあって、その異常なデータのタイミングで例外が出ている可能性（avatar追加する前に作っていたデータが原因とか）
* ソースコード自体に問題があるケース

があり得そうなので、どちらにせよ #index とかよりは #showみたいな1件ずつチェックできるURLでチェックする方が切り分けしやすいかなと思います。

また、web-consoleとかのデバッガを使って例外発生の瞬間のコンテキストから実際に異常が発生している原因を追いかけるという方法もありそう（繰り返しですが

2023-08-28 09:20 UTC, cellotak commented on app/views/users/_user.html.erb
> +
`user.avatar.persisted?` がnilかどうかで条件分岐すれば表示できるようになりました。

2023-08-29 04:03 UTC, cellotak commented on config/application.rb
> +    config.active_storage.variant_processor = :vips
- `:vips`とした場合のRailsログ
```  
LoadError (Could not open library 'vips.so.42': vips.so.42: cannot open shared object file: No such file or directory.
Could not open library 'libvips.so.42': libvips.so.42: cannot open shared object file: No such file or directory):
```

- `:mini_magick`とした場合のRailsログ
```
MiniMagick::Error (You must have ImageMagick or GraphicsMagick installed):
```

- `:image_processing`とした場合のRailsログ

```
NoMethodError (undefined method `source' for ImageProcessing:Module):
```

2023-08-30 03:44 UTC, cellotak commented on config/application.rb
> +    config.active_storage.variant_processor = :vips
OS側にlibvipsをインストールすることで解決しました。

2023-08-30 08:19 UTC, konaga-k requested changes
動作確認できてないですが、ざっと見て気になるところをコメントしました！

2023-08-30 08:19 UTC, konaga-k commented on app/models/user.rb
> +    errors.add(:avatar, I18n.t('errors.messages.file_type_not_image')) unless image?
[SHOULD]
`#image?` というメソッド名が気になりました
メソッドの内容がアバターのチェックであるのに対し、メソッド名が `User#image?` だとユーザー全体についてのチェックのように見えて、内容と名前が釣り合っていないように見えました

何をチェックしているか分かる名前に変えるのがよさそうです

2023-08-30 08:19 UTC, konaga-k commented on app/models/user.rb
> +  def validate_file_type
[コメント]
このメソッドについては、どういう意図でメソッドを設けたのかで、適切な名前が決まってきそうです

「Userモデルのすべてのファイル属性のタイプをチェックする」という意図なのであれば、このメソッド名でも問題ないと思います
（その場合、今後ファイル属性が増えていったら、このメソッド内にチェック処理を増やすことになる）

一方で、もし「アバターのみのファイルタイプをチェックする」という意図だったのであれば、「アバターのみチェックする」ことが分かるメソッド名にしたほうが良さそうです

2023-08-30 08:19 UTC, konaga-k commented on app/controllers/users_controller.rb
> +    @users = User.with_attached_avatar.order(:id).page(params[:page])
👍

2023-08-30 08:19 UTC, konaga-k commented on app/views/devise/registrations/_profile_fields.html.erb
> +    <% if @user.avatar.persisted? %>
[MAY]
機能的には問題ないと思いますが、ActiveStorageのファイル有無チェックには `#attached?` を使う方がよさそうです
https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html#method-i-attached-3F

他の箇所では `#attached?` を使っているので、メソッドを知らないわけではないのかな？と思いました
https://github.com/cellotak/fjord-books_app-2023/blob/4c9b466ade91666c8268beae12f9e78cb9d1a9ad/app/models/user.rb#L12

もし `#persisted?` でないといけなかった理由があれば教えてくださいー

2023-08-30 08:19 UTC, konaga-k commented on config/locales/translation_ja.yml
> +
[SHOULD]
ファイル末尾には改行を入れてもらえると
行は「文字+改行」で成り立つようなので
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206

IDE等で予め設定しておくと、ファイル末尾へ自動的に改行挿入されるようになると思います

2023-08-30 08:23 UTC, konaga-k commented on config/locales/translation_ja.yml
> +
いや、19行目が空行だから問題ないのか
すみません、差分の方に空行がないときの「-」マークが出てたので誤解しました……
![image](https://github.com/cellotak/fjord-books_app-2023/assets/54785890/a7ec72ae-52b8-41f1-babf-0e7419c2bfe0)

2023-09-01 01:45 UTC, cellotak commented on app/models/user.rb
> +  def validate_file_type
Bookモデルにも画像データのカラムがありますがそこはチェックしていないので「アバターのみのファイルタイプをチェックする」で間違いないです。
ということで `validate_avatar_file_type`にしてみました。

2023-09-01 02:05 UTC, cellotak commented on app/views/devise/registrations/_profile_fields.html.erb
> +    <% if @user.avatar.persisted? %>
単純に、その部分を書いているときに`#persisit?`を見つけて使いましたが、validationの部分を書くときに`attached?`を見つけて使い、そのままどちらかに統一すべきだということに気づかなかった、という経緯です。ですので`#persisted?`にしている理由は特にありません。

`#attached?`にすべき理由ですが、「一般的にDBにデータが登録済みかどうかを調べたいときは`#persisted?`を使えばいいが、ActiveStrageを使っているならその枠組みで使えるものを使った方がよい」という考えであってますでしょうか？

2023-09-01 02:14 UTC, cellotak commented on config/locales/translation_ja.yml
> +
確認したら、19行目が半角スペース1個紛れてしまっていたので空行扱いになっていませんでした。こちらの確認不足です。(rbファイルだとrubocopが怒ってくれますが、yamlはスルーされてしまう。)
GitHubでもFiles Changedをよく確認すれば防げる間違いだったので気を付けます。

それとIDEやエディタでファイル末尾に改行が入れられるという点について、考えたらその機能がないはずないのに、全然気づいていませんでした。
ありがとうございます。

2023-09-01 04:25 UTC, konaga-k reviewed
コメントありがとうございます！
ちょっと返信しましたが、新しい指摘事項はありません！

2023-09-01 04:25 UTC, konaga-k commented on app/models/user.rb
> +  def validate_file_type
cellotakさんの想定しているメソッドの責務範囲については了解です！

ただ、
> Bookモデルにも画像データのカラムがありますがそこはチェックしていないので

について、UserモデルのメソッドからBookモデルのカラムをチェックする必要は（基本的に）ないです
なので、`book.picture` のチェックをしないからといって、「アバターのみのファイルタイプをチェックする」メソッドにしないといけないわけではない、ということだけ補足しておきます

2023-09-01 04:25 UTC, konaga-k commented on app/views/devise/registrations/_profile_fields.html.erb
> +    <% if @user.avatar.persisted? %>
経緯は了解しました！

`#attached?` の方が良い理由もあってます！
が、このviewで使うのは多分 `#persisted?` の方がいいです。指摘撤回します🙇‍♂
調べてて気づきました、すみません！

長くなりますが説明してみますね

---
そもそもActiveStorageの文脈での `#persisted?` と `#attached?` って微妙に意味が違っています
`#attached?` の場合、ファイルが一度添付されていれば、DBやストレージに保存されなくてもtrueを返すようになっています
（このあたり、[APIドキュメント](https://api.rubyonrails.org/classes/ActiveStorage/Attached/One.html)の説明文上で厳密に書かれてないので、すごい分かりづらい挙動だと思います。ただ、実際に動作確認するとそういう風になっています）

これがどう影響するかというと、「ユーザー登録画面で画像を添付してアカウント登録しようとしたが、バリデーションエラーが起きて保存に失敗したとき」の挙動が変わります
* `user.avatar.persisted?` -> falseになる（保存には失敗している）
* `user.avatar.attached?` -> trueになる（添付だけは実行している）

なので `#attached?` を使う場合、バリデーションエラー後のアカウント登録画面で`image_tag` が呼び出されます
が、実際に動作確認したところ、エラーにはならないものの、画像表示はされません
![image](https://github.com/cellotak/fjord-books_app-2023/assets/54785890/0c8871ac-6d44-42ba-8974-f4da484ca5b7)

おそらく、 `image_tag` が生成する画像参照先のURLにファイルの実体がないので、画像表示できない、ということだと思ってます
あんまり深掘りできてませんが

画像表示失敗の状態をユーザーに見せる方が微妙なので、画像の表示条件には、現状通り `#persisted?` を使ったほうがよさそうです

2023-09-01 06:33 UTC, cellotak commented on app/models/user.rb
> +  def validate_file_type
ちょっとズレた回答をしてしまっていました。
「Userモデルで仮に他のファイル属性が追加されたとしても、このメソッドでタイプチェックするつもりはないので、このメソッドではアバターのみのファイルタイプをチェックする、で間違いないです。」
というのが回答として正しそうですね。

Bookモデルの話とは話が別でした。

2023-09-01 06:33 UTC, cellotak commented on app/views/devise/registrations/_profile_fields.html.erb
> +    <% if @user.avatar.persisted? %>
詳細まで説明頂きありがとうございます！

`#persisted?`と`#attached?`が説明して下さった仕様なのであれば、

> 「画像表示失敗の状態をユーザーに見せる方が微妙」

という理由もそうですが、そもそも「現在のアイコン画像」として表示したいのはあくまでも既に登録済みの画像であって、フォームに添付した画像ではないので、おっしゃる通り`#persisted?`を使うのが適切と感じます。
(`#persisted?`と`#attached?の違いについてはドキュメントみてもあまりピンとこないですし、挙動を自分で確認もしていないので説明を鵜呑みした前提で話してます )

結果的にコードは変更することなさそうですが、まったくそこまで考えが及んでいなかったので、非常に学びになりました。

2023-09-01 06:33 UTC, cellotak commented on app/views/users/_user.html.erb
> +    <% end %>
@konaga-k 

ついでに気になってしまったので伺います。
この部分でも `#persisted?`を使っていますが、ここもあくまでもDBに保存されているデータを表示させたいので `#persisted?`の方が意味合い的に適切と考えていますが、合っているでしょうか。

(とはいえこのビューが呼び出されるときに「DBに保存されていないが添付はされている」という状況は発生しえないはずなので挙動には影響しないですが)

2023-09-07 08:42 UTC, cellotak commented on app/models/user.rb
> +    errors.add(:avatar, I18n.t('errors.messages.file_type_not_image')) unless image?
`avatar_is_image?`に変更してみました。
「メソッド名をselfを主語とする動詞で始める」という原則には沿っていないですが、長尾さん自身がおっしゃったようにprivateメソッドなので`user.avatar_is_image?`と呼び出されることはないため、これでいいかと考えています。

2023-09-07 12:31 UTC, u1tnk approved these changes
コメントしましたが細かいところなのでapproveとします 👍

2023-09-07 12:31 UTC, u1tnk commented on app/models/user.rb
> +  def avatar_is_image?
名前は良さそうですね 👍

2023-09-07 12:31 UTC, u1tnk commented on app/views/users/_user.html.erb
> +    <% end %>
微妙なところですねー。
レコード自体が保存されているのが前提のページなので、このページでは `attached?` がどちらかというと適切な気はします。

2023-09-08 02:22 UTC, konaga-k approved these changes
メソッド名を修正してもらったのでapproveします！
`#attached?` / `#persisted?` の話は修正優先度低い、直したいならこのPRでまとめて直してもらってもいい、くらいの感じです

2023-09-08 02:22 UTC, konaga-k commented on app/models/user.rb
> +  def avatar_is_image?
👍

2023-09-08 02:22 UTC, konaga-k commented on app/views/users/_user.html.erb
> +    <% end %>
個人的にはこんな感じですね
- ActiveSotrageのファイル存在チェックでは、基本として `#attached?` を使う
- レコード保存の有無が挙動に関わる状況なら `#persisted?` を使う

なのでこのコードの最善を追求するなら `#attached?` かなあと

2023-09-11 09:21 UTC, merged